SistControl/SistControl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('catalogo/', include(('catalogos.urls', 'catalogos'), namespace='categorias')),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    
]

SistControl/compras/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('proveedores/', Proveedores.as_view(), name='lista_proveedores'),
    path('proveedores/nuevo/', NuevoProveedor.as_view(), name='nuevo_proveedor'),
    path('proveedores/editar/<int:pk>', EditarProveedor.as_view(), name='editar_proveedor'),
    path('proveedores/inactiv/<int:id>', inactivar_proveedor, name='inactivar_proveedor'),

    path('compras/', Compras.as_view(), name='lista_compras'),
    path('compras/nuevo', compraview, name='compras_new'),
    path('compras/editar/<int:compra_id>', compraview, name = 'editar_compras'),

]

SistControl/core/urls.py
from django.urls import path
from .views import Home, Denegado
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', Home.as_view(), name='home'),
#Esta es otra forma de configurar las URL para busqueda inversa
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/login.html'), name='logout'),
    path('denegado/', Denegado.as_view(), name='denegado'),
]

SistControl/compras/models.py
from django.db import models
from core.models import ClaseModelo
from catalogos.models import Productos

# Create your models here.
class Proveedor(ClaseModelo):
    nombre = models.CharField(max_length=150, verbose_name='Nombre Proveedor', unique=True)
    direccion = models.CharField(max_length=250, null=True, blank=True)
    contacto = models.CharField(max_length=75, verbose_name='Persona de contacto', null=True, blank=True)
    telefono = models.CharField(max_length=12, verbose_name='Teléfono', null=True, blank=True)
    email = models.EmailField(max_length=254, verbose_name='Correo electrónico', null=True, blank=True)

    def __str__(self):
        return self.nombre
    
    def save(self):
        self.nombre = self.nombre.upper()
        super(Proveedor, self).save()
    
    class Meta:
        verbose_name = 'proveedor'
        verbose_name_plural = 'proveedores'
        ordering = ['nombre']

class ComprasEncabezado(ClaseModelo):
    fecha_compra = models.DateField(null=True, blank=True)
    observaciones = models.TextField(blank=True, null=True)
    no_fact = models.CharField(max_length=100)
    fecha_factura = models.DateField()
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    iva = models.FloatField(default=0)
    total = models.FloatField(default=0)


    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return self.observaciones
    
    def save(self):
        self.observaciones = self.observaciones.upper()
        self.iva = ((self.sub_total - self.descuento) / 1.12)*0.12
        self.total = self.sub_total - self.descuento
        super(ComprasEncabezado, self).save()
    
    class Meta:
        verbose_name = 'Encabezado de compra'
        verbose_name_plural = 'Encabezados de compras'

class ComprasDetalle(ClaseModelo):
    compra = models.ForeignKey(ComprasEncabezado, on_delete=models.CASCADE)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    cantidad = models.FloatField(default=0)
    precio_comp = models.FloatField(default=0)
    iva = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def __str__(self):
        return self.producto
    
    def save(self):
        self.sub_total = float(self.cantidad) * float(self.precio_comp)
        self.iva = ((self.sub_total-self.descuento)/1.12)*0.12
        self.total = self.sub_total-self.descuento
        super(ComprasDetalle, self).save()
       
    class Meta:
        verbose_name = 'Detalle de compra'

SistControl/compras/forms.py
from django import forms
from .models import *

class FormProveedor(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields=['nombre', 'direccion', 'contacto', 'telefono', 'email', 'estado']
        widget = {'descripcion':forms.TextInput}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })

class FormCompraEnc(forms.ModelForm):
    fecha_compra = forms.DateInput()
    fecha_factura = forms.DateInput()
    

    class Meta:
        model = ComprasEncabezado
        fields = [
            'proveedor', 'fecha_compra',
            'observaciones', 'no_fact', 'fecha_factura', 'sub_total','descuento', 'iva', 'total'
        ]
    #Cambiamos los atributos de los objetos que conforman el form
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})
        
        #Convertimos los campos a solo lectura
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['iva'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

SistControl/compras/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.db.models import Sum
from core.views import SinAcceso
from catalogos.models import Productos
from .forms import *
from .models import *
import json
import datetime

# Create your views here.
class Proveedores(SinAcceso, generic.ListView):
    permission_required = 'compras.view_proveedores' 
    model = Proveedor
    template_name = 'compras/lista_proveedores.html'
    context_object_name = 'proveedores'

class NuevoProveedor(SuccessMessageMixin ,SinAcceso, generic.CreateView):
    permission_required = 'compras.add_proveedores'
    model = Proveedor
    template_name = 'compras/form_proveedores.html'
    context_object_name = 'proveedores'
    form_class = FormProveedor
    success_url = reverse_lazy('compras:lista_proveedores')
    success_message = 'Se ha creado un nuevo proveedor'

    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)

class EditarProveedor(SuccessMessageMixin ,SinAcceso, generic.UpdateView):
    permission_required = 'compras.change_proveedores'
    model=Proveedor
    template_name="compras/form_proveedores.html"
    context_object_name = 'proveedores'
    form_class=FormProveedor
    success_url = reverse_lazy('compras:lista_proveedores')
    success_message = 'Se ha actualizado el proveedor'

    def form_valid(self, form):
        form.instance.modificador = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('copras.change_proveedores', login_url='core:denegado')
def inactivar_proveedor(request, id):
    prov = Proveedor.objects.filter(pk=id).first()
    contexto={}
    template_name="compras/delete.html"

    if not prov:
        return HttpResponse('No existe el proveedor ' + str(id))

    if request.method == 'GET':
        contexto ={'proveedores':prov}

    if request.method == 'POST':
        prov.estado = False
        prov.save()
        messages.success(request, 'Se ha inactivado el proveedor')
        return redirect("compras:lista_proveedores")

    return render(request,template_name,contexto)

class Compras(SinAcceso, generic.ListView):
    permission_required = 'compras.view_comprasencabezado' 
    model = ComprasEncabezado
    template_name = 'compras/lista_compras.html'
    context_object_name = 'comp'

@login_required(login_url='/login/')
@permission_required('copras.change_comprasencabezado', login_url='core:denegado')
def compraview(request, compra_id=None):
    template_name = 'compras/compras.html'
    prod = Productos.objects.filter(estado=True)
    form_compras = {}
    contexto = {}

    if request.method == 'GET':
        form_compras = FormCompraEnc()
        enc = ComprasEncabezado.objects.filter(pk=compra_id).first()
        #Si existe el encabezado...
        if enc:
            detalle = ComprasDetalle.objects.filter(compra=enc)
            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            fecha_factura = datetime.date.isoformat(enc.fecha_factura)
            e = {
                'fecha_compra':fecha_compra,
                'proveedor':enc.proveedor,
                'fecha_factura':fecha_factura,
                'no_fact':enc.no_fact,
                'observaciones':enc.observaciones,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'iva':enc.iva,
                'total':enc.total
            }
            #Inicializa el formulario con los campos que le asignamos a la variable e
            form_compras = FormCompraEnc(e)
        else:
            detalle = None
        
        contexto = {'productos':prod, 'encabezado':enc, 'detalle':detalle, 'form_enc':form_compras}

    if request.method == 'POST':
#Si es un POST, capturamos los datos que se encuentran en el form
    #Iniciamos con los datos del encabezado
        fecha_compra = request.POST.get('fecha_compra')
        proveedor = request.POST.get('proveedor')
        fecha_factura = request.POST.get('fecha_factura')
        no_fact = request.POST.get('no_fact')
        observaciones = request.POST.get('observaciones')
        sub_total = 0
        descuento = 0
        iva = 0
        total = 0

        if not compra_id:
            prov = Proveedor.objects.get(pk=proveedor)
            #Usando los campos definidos en el modelo
            enc = ComprasEncabezado(
                fecha_compra = fecha_compra,
                observaciones = observaciones,
                no_fact = no_fact,
                fecha_factura = fecha_factura,
                proveedor = prov,
                creador = request.user
            )
            if enc:
                enc.save()
                compra_id = enc.id
        else:
            enc = ComprasEncabezado.objects.filter(pk=compra_id).first()
            if enc:
                enc.fecha_compra = fecha_compra
                enc.fecha_factura = fecha_factura
                enc.observaciones = observaciones
                enc.no_fact = no_fact
                enc.save()
        
        if not compra_id:
            return redirect('compras:lista_compras')

#Ahora van los datos del detalle
        producto = request.POST.get('id_id_producto')
        cantidad = request.POST.get('id_cantidad_detalle')
        precio = request.POST.get('id_precio_detalle')
        sub_total_detalle = request.POST.get('id_sub_total_detalle')
        descuento_detalle = request.POST.get('id_descuento_detalle')
        total_detalle = request.POST.get('id_total_detalle')

        prod = Productos.objects.get(pk=producto)

        det = ComprasDetalle(
            compra = enc,
            producto = prod,
            cantidad = cantidad,
            precio_comp = precio,
            sub_total = sub_total_detalle,
            descuento = descuento,
            total = total,
            creador = request.user
        )
    #Si se han obtenido los datos, lo guardamos
        if det:
            det.save()
            sub_total = ComprasDetalle.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento = ComprasDetalle.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            enc.sub_total = sub_total["sub_total__sum"]
            enc.descuento = descuento["descuento__sum"]
            enc.save()
        
        return redirect('compras:editar_compras', compra_id=compra_id)

    return render(request, template_name, contexto)

SistControl/compras/templates/compras/delete.html
<div class="modal-dialog modal-xs">
    <div class="modal-content">
        <form method="POST" class="form-inline">
        {% csrf_token %}
            <div class="col-xl-12 col-md-6 mb-6">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Inactivar {{proveedores.nombre}}?</div>
                                <button id="btnInactivar" type="button" class="btn btn-danger mt-3"><i class="fas fa-question-circle"></i> Inactivar</button>
                                <button type="button" class="btn btn-success mt-3" onclick="return cerrar_modal()">Cancelar</button>
                            </div>
                            <div class="col-auto">
                                <i class="far fa-question-circle fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready(function(){
    var token = $('input[name=csrfmiddlewaretoken]').val();
  $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", token);
            }
        }
    });
  
  $("#btnInactivar").click(function(e){
      e.preventDefault();
      //alert("Probando");

      var id = {{ proveedores.id }};
      var template="{% url 'compras:inactivar_proveedor' proveedores.id %}";
      //template += id;
      var data = {"id":id};
      data = JSON.stringify(data);

      $.ajax({
        type: "POST",
        url: template,
        data: data,
        beforeSend: function(xhr,settings){
          $.ajaxSettings.beforeSend(xhr,settings);
        },
        success: function(response){
          console.log(response);
          cerrar_modal();
          //alert(response);
          var color = (response.startsWith('No existe el proveedor')? 'red':'green');
          mensaje(response, color);
        },
        error: function(jqXHR, textStatus, errorThrow){
          console.log(textStatus, errorThrow);
          mensaje(errorThrow,'red');
          cerrar_modal();
        }
      });
  });

});
</script>

SistControl/compras/templates/compras/form_proveedores.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
    {% if proveedores %}
        <form method="POST" role="form" class="form-inline" action="{% url 'compras:editar_proveedor' proveedores.pk %}">
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'compras:nuevo_proveedor' %}">
        {% endif %}
            {% csrf_token %}
            <div class="col-xl-15 col-md-12 mb-12">
                {% if productos %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if productos %} Editar {% else %} Nuevo {% endif %} Proveedor
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                {{form.as_p}}
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                    <button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

SistControl/compras/templates/compras/lista_compras.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Compras</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" href="{% url 'compras:compras_new' %}"><i class="far fa-calendar-plus"></i> Nueva compra</a>
                      <div class="dropdown-divider"></div>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                {% if not comp %}
                <div class="alert alert-info">No hay compras para mostrar</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Fecha de compra</th>
                        <th>No. Fact</th>
                        <th>Fecha Factura</th>
                        <th>Observaciones</th>
                        <th>Total de compra</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for compra in comp %}
                        <tr>
                            <td>{{compra.id}}</td>
                            <td>{{compra.fecha_compra}}</td>
                            <td>{{compra.no_fact}}</td>
                            <td>{{compra.fecha_factura}}</td>
                            <td>{{copra.observaciones}}</td>
                            <td>{{compra.total}}</td>
                            <td>
                            <a class="btn btn-warning btn-circle" href="{% url 'compras:editar_compras' compra.id %}"><i class="far fa-edit"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
              </div>

{% endblock content %}

{% block js_page %}
 <script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock js_page %}

SistControl/compras/templates/compras/lista_proveedores.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Proveedores</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" onclick="return abrir_modal('{% url 'compras:nuevo_proveedor' %}')" href="#"><i class="far fa-calendar-plus"></i> Crear</a>
                      <div class="dropdown-divider"></div>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                {% if not proveedores %}
                <div class="alert alert-info">No hay proveedores para mostrar</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Dirección</th>
                        <th>Contacto</th>
                        <th>Teléfono</th>
                        <th>E-mail</th>
                        <th>Estado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for proveedor in proveedores %}
                        <tr>
                            <td>{{proveedor.id}}</td>
                            <td>{{proveedor.nombre}}</td>
                            <td>{{proveedor.direccion}}</td>
                            <td>{{proveedor.contacto}}</td>
                            <td>{{proveedor.telefono}}</td>
                            <td>{{proveedor.email}}</td>
                            <td>{{proveedor.estado|yesno:"Activo, Inactivo"}}</td>
                            <td>
                            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'compras:editar_proveedor' proveedor.id %}');"><i class="far fa-edit"></i></button>
                            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'compras:inactivar_proveedor' proveedor.id %}');"><i class="far fa-thumbs-down"></i></button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
              </div>

{% endblock content %}

{% block js_page %}
 <script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock js_page %}