SistControl/SistControl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('catalogo/', include(('catalogos.urls', 'catalogos'), namespace='categorias')),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    
]

SistControl/catalogos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('categorias/', Categoria.as_view(), name='lista_categoria'),
    path('categorias/nuevo/', NuevoCategoria.as_view(), name='nueva_categoria'),
    path('categorias/editar/<int:pk>', EditarCategoria.as_view(), name='editar_categoria'),
    path('categorias/borrar/<int:pk>', BorrarCategoria.as_view(), name='borrar_categoria'),

    path('subcategorias/', SubCategorias.as_view(), name='lista_subcategoria'),
    path('subcategorias/nuevo/', NuevoSubCategoria.as_view(), name='nueva_subcategoria'),
    path('subcategorias/editar/<int:pk>', EditarSubCategoria.as_view(), name='editar_subcategoria'),
    path('subcategorias/borrar/<int:pk>', BorrarSubCategoria.as_view(), name='borrar_subcategoria'),

    path('marcas/', Marca.as_view(), name='lista_marcas'),
    path('marcas/nuevo/', NuevaMarca.as_view(), name='nueva_marca'),
    path('marcas/editar/<int:pk>', EditarMarca.as_view(), name='editar_marca'),
    path('marcas/inactiv/<int:id>', inactivar, name='inactivar_marca'),

    path('ums/', UMVista.as_view(), name='lista_um'),
    path('ums/nuevo/', NuevaUM.as_view(), name='nueva_um'),
    path('ums/editar/<int:pk>', EditarUMS.as_view(), name='editar_um'),
    path('ums/inactiv/<int:id>', inactivarUM, name='inactivar_um'),

    path('productos/',Producto.as_view(), name="lista_producto"),
    path('productos/nuevo',NuevoProducto.as_view(), name="nuevo_producto"),
    path('productos/editar/<int:pk>',EditarProducto.as_view(), name="editar_producto"),
    path('productos/inactiv/<int:id>',inactivar_producto, name="inactivar_producto"),

]

SistControl/core/urls.py
from django.urls import path
from .views import Home, Denegado
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', Home.as_view(), name='home'),
#Esta es otra forma de configurar las URL para busqueda inversa
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/login.html'), name='logout'),
    path('denegado/', Denegado.as_view(), name='denegado'),
]

SistControl/core/models.py
from django.db import models
from django.contrib.auth.models import User

#Este modelo es la base para otros modelos usados en otras aplicaciones
class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    modificador = models.IntegerField(blank=True, null=True)

    class Meta:
    #Le indicamos que no haga migraciones de este modelo
        abstract = True

SistControl/catalogos/forms.py
from django import forms
from .models import *

class FormCategoria(forms.ModelForm):
    class Meta:
        model = Categorias
        fields=['nombre', 'estado']
        labels = {'nombre':'Nombre categoria', 'estado':'Activo/Inactivo'}
        widget = {'descripcion':forms.TextInput}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })

class FormSubCategoria(forms.ModelForm):
    #Muestra solo las categorias activas
    categoria = forms.ModelChoiceField(queryset=Categorias.objects.filter(estado=True).order_by('nombre'))
    class Meta:
        model = SubCategoria
        fields=['categoria', 'nombre', 'estado']
        labels = {'nombre':'Subcategoria', 'estado':'Activo/Inactivo'}
        widget = {'descripcion':forms.TextInput}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
            self.fields['categoria'].empty_label = "Selecciona la categoría"

class FormMarca(forms.ModelForm):
    class Meta:
        model = Marcas
        fields=['nombre', 'estado']
        labels = {'nombre':'Marca', 'estado':'Activo/Inactivo'}
        widget = {'descripcion':forms.TextInput}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })

class FormUm(forms.ModelForm):
    class Meta:
        model = UnidadMedida
        fields=['nombre', 'estado']
        labels = {'nombre':'UM', 'estado':'Activo/Inactivo'}
        widget = {'descripcion':forms.TextInput}

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })

class FormProductos(forms.ModelForm): 
    class Meta:
        model=Productos
        fields=['codigo','codigo_barra','nombre','estado', \
                'precio','existencia','ultima_compra',
                'marca','subcategoria','unidad_medida']
        exclude = ['modificador','updated','creador','created']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

SistControl/catalogos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from django.urls import reverse_lazy
from core.views import SinAcceso
from .models import *
from .forms import *

# Create your views here.
class Categoria(SinAcceso, generic.ListView):
    permission_required = 'catalogos.view_categorias'    
    model = Categorias
    template_name = 'catalogos/lista_categoria.html'
    context_object_name = 'categorias'
    

class NuevoCategoria(SuccessMessageMixin, SinAcceso, generic.CreateView):
    permission_required = 'catalogos.add_categorias'
    model = Categorias
    template_name = 'catalogos/form_categoria.html'
    context_object_name = 'categorias'
    form_class = FormCategoria
    success_url = reverse_lazy('categorias:lista_categoria')
    success_message = 'Se ha creado una nueva categoría'

#Agregamos el Id del usuario que crea la categoría
    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)

class EditarCategoria(SuccessMessageMixin, SinAcceso, generic.UpdateView):
    permission_required = 'catalogos.change_categorias'
    model = Categorias
    template_name = 'catalogos/form_categoria.html'
    context_object_name = 'categorias'
    form_class = FormCategoria
    success_url = reverse_lazy('categorias:lista_categoria')
    success_message = 'Se ha modificado categoría'


#Agregamos el Id del usuario que crea la categoría
    def form_valid(self, form):
        form.instance.modificador = self.request.user.id
        return super().form_valid(form)

class BorrarCategoria(LoginRequiredMixin, generic.DeleteView):
    model = Categorias
    template_name = 'catalogos/delete.html'
    context_object_name = 'categorias'
    success_url = reverse_lazy('categorias:lista_categoria')
    login_url = 'core:login'

class SubCategorias(SinAcceso, generic.ListView):
    permission_required = 'catalogos.view_subcategoria'
    model = SubCategoria
    template_name = 'catalogos/lista_subcategoria.html'
    context_object_name = 'subcategorias'

class NuevoSubCategoria(SuccessMessageMixin, SinAcceso, generic.CreateView):
    permission_required = 'catalogos.add_subcategoria'
    model = SubCategoria
    template_name = 'catalogos/form_subcategoria.html'
    context_object_name = 'subcategorias'
    form_class = FormSubCategoria
    success_url = reverse_lazy('categorias:lista_subcategoria')
    success_message = 'Se ha creado una nueva subcategoría'


#Agregamos el Id del usuario que crea la categoría
    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)

class EditarSubCategoria(SuccessMessageMixin, SinAcceso, generic.UpdateView):
    permission_required = 'catalogos.change_categorias'
    model = SubCategoria
    template_name = 'catalogos/form_subcategoria.html'
    context_object_name = 'categorias'
    form_class = FormSubCategoria
    success_url = reverse_lazy('categorias:lista_subcategoria')
    success_message = 'Se ha modificado la categoría'


#Agregamos el Id del usuario que crea la categoría
    def form_valid(self, form):
        form.instance.modificador = self.request.user.id
        return super().form_valid(form)

class BorrarSubCategoria(LoginRequiredMixin, generic.DeleteView):
    model = SubCategoria
    template_name = 'catalogos/delete.html'
    context_object_name = 'categorias'
    success_url = reverse_lazy('categorias:lista_subcategoria')
    login_url = 'core:login'

class Marca(SinAcceso, generic.ListView):
    permission_required = 'catalogos.view_marcas'
    model = Marcas
    template_name = 'catalogos/lista_marca.html'
    context_object_name = 'marcas'

class NuevaMarca(SuccessMessageMixin, SinAcceso, generic.CreateView):
    permission_required = 'catalogos.add_marcas'
    model = Marcas
    template_name = 'catalogos/form_marca.html'
    context_object_name = 'marcas'
    form_class = FormMarca    
    success_url = reverse_lazy('categorias:lista_marcas')
    success_message = 'Se ha creado una nueva marca'


    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)

class EditarMarca(SuccessMessageMixin, SinAcceso, generic.UpdateView):
    permission_required = 'catalogos.change_marcas'
    model = Marcas
    template_name = 'catalogos/form_marca.html'
    context_object_name = 'marcas'
    form_class = FormMarca    
    success_url = reverse_lazy('categorias:lista_marcas')
    success_message = 'Se ha modificado la marca'


    def form_valid(self, form):
        form.instance.modificador = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('catalogos.change_marcas', login_url='core:denegado')
def inactivar(request, id):
    marca = Marcas.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'catalogos/delete.html'

    if not marca:
        return redirect('categorias:lista_marcas')
    
    if request.method=='GET':
        contexto={'categorias':marca}
    
    if request.method=='POST':
        marca.estado = False
        marca.save()
        messages.success(request, 'Se ha inactivado la marca')
        return redirect('categorias:lista_marcas')
    
    return render(request,template_name, contexto)

class UMVista(SinAcceso, generic.ListView):
    permission_required = 'catalogos.view_unidadmedida'
    model = UnidadMedida
    template_name = 'catalogos/lista_um.html'
    context_object_name = 'UMS'

class NuevaUM(SuccessMessageMixin, SinAcceso, generic.CreateView):
    permission_required = 'catalogos.add_unidadmedida'
    model = UnidadMedida
    template_name = 'catalogos/form_um.html'
    context_object_name = 'UMS'
    form_class = FormUm  
    success_url = reverse_lazy('categorias:lista_um')
    success_message = 'Se ha creado una nueva unidad de medida'


    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)

class EditarUMS(SuccessMessageMixin, SinAcceso, generic.UpdateView):
    permission_required = 'catalogos.change_unidadmedida'
    model = UnidadMedida
    template_name = 'catalogos/form_um.html'
    context_object_name = 'UMS'
    form_class = FormUm   
    success_url = reverse_lazy('categorias:lista_um')
    success_message = 'Se ha modificado la unidad de medida'


    def form_valid(self, form):
        form.instance.modificador = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('catalogos.change_unidadmedida', login_url='core:denegado')
def inactivarUM(request, id):
    um = UnidadMedida.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'catalogos/delete.html'

    if not um:
        return redirect('categorias:lista_um')
    
    if request.method=='GET':
        contexto={'categorias':um}
    
    if request.method=='POST':
        um.estado = False
        um.save()
        messages.success(request, 'Se ha inactivado la unidad de medida')
        return redirect('categorias:lista_um')
    
    return render(request,template_name, contexto)

class Producto(SinAcceso, generic.ListView):
    permission_required = 'catalogos.view_productos'
    model = Productos
    template_name = "catalogos/lista_producto.html"
    context_object_name = "productos"


class NuevoProducto(SuccessMessageMixin, SinAcceso, generic.CreateView):
    permission_required = 'catalogos.add_productos'
    model=Productos
    template_name="catalogos/form_productos.html"
    context_object_name = 'productos'
    form_class=FormProductos
    success_url = reverse_lazy('categorias:lista_producto')
    success_message = 'Se ha creado un nuevo producto'


    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)
    

class EditarProducto(SuccessMessageMixin, SinAcceso, generic.UpdateView):
    permission_required = 'catalogos.change_productos'
    model=Productos
    template_name="catalogos/form_productos.html"
    context_object_name = 'productos'
    form_class=FormProductos
    success_url = reverse_lazy('categorias:lista_producto')
    success_message = 'Se ha modificado el producto'


    def form_valid(self, form):
        form.instance.modificador = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('catalogos.change_productos', login_url='core:denegado')
def inactivar_producto(request, id):
    prod = Productos.objects.filter(pk=id).first()
    contexto={}
    template_name="catalogos/delete.html"

    if not prod:
        return redirect("categorias:lista_producto")
    
    if request.method=='GET':
        contexto={'categorias':prod}
    
    if request.method=='POST':
        prod.estado=False
        prod.save()
        messages.success(request, 'Se ha inactivado el producto')
        return redirect("categorias:lista_producto")

    return render(request,template_name,contexto)

SistControl/catalogos/templates/catalogos/lista_categoria.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Categorías</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" href="{% url 'categorias:nueva_categoria' %}"><i class="far fa-calendar-plus"></i> Crear</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                {% if not categorias %}
                <div class="alert alert-info">No hay categorías para mostrar</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Creado</th>
                        <th>Modificado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for categ in categorias %}
                        <tr>
                            <td>{{categ.id}}</td>
                            <td>{{categ.nombre}}</td>
                            <td>{{categ.estado|yesno:"Activo, Inactivo"}}</td>
                            <td>{{categ.created|date:"d/m/y H:i:s"}}</td>
                            <td>{{categ.updated|date:"d/m/y H:i:s"}}</td>
                            <td>
                            <a href="{% url 'categorias:editar_categoria' categ.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'categorias:borrar_categoria' categ.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
              </div>

{% endblock content %}

{% block js_page %}
  <script>
  //Inicializa los plugins de jquery
  $(document).ready(function() {
    $('.table').DataTable();
  });
  </script> 
{% endblock js_page %}

SistControl/catalogos/templates/catalogos/lista_marca.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Marcas</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" href="{% url 'categorias:nueva_marca' %}"><i class="far fa-calendar-plus"></i> Crear</a>
                      <div class="dropdown-divider"></div>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                {% if not marcas %}
                <div class="alert alert-info">No hay marcas para mostrar</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Creado</th>
                        <th>Modificado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for marca in marcas %}
                        <tr>
                            <td>{{marca.id}}</td>
                            <td>{{marca.nombre}}</td>
                            <td>{{marca.estado|yesno:"Activo, Inactivo"}}</td>
                            <td>{{marca.created|date:"d/m/y H:i:s"}}</td>
                            <td>{{marca.updated|date:"d/m/y H:i:s"}}</td>
                            <td>
                            <a href="{% url 'categorias:editar_marca' marca.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'categorias:inactivar_marca' marca.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
              </div>

{% endblock content %}

{% block js_page %}
 <script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock js_page %}

SistControl/catalogos/templates/catalogos/lista_producto.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Productos</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" onclick="return abrir_modal('{% url 'categorias:nuevo_producto' %}')" href="#"><i class="far fa-calendar-plus"></i> Crear</a>
                      <div class="dropdown-divider"></div>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                {% if not productos %}
                <div class="alert alert-info">No hay productos para mostrar</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Código</th>
                        <th>Código de barras</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>UM</th>
                        <th>Existencias</th>
                        <th>Marca</th>
                        <th>Subcategoria</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                        <tr>
                            <td>{{producto.codigo}}</td>
                            <td>{{producto.codigo_barra}}</td>
                            <td>{{producto.nombre}}</td>
                            <td>{{producto.precio}}</td>
                            <td>{{producto.unidad_medida}}</td>
                            <td>{{producto.existencia}}</td>
                            <td>{{producto.marca}}</td>
                            <td>{{producto.subcategoria}}</td>
                            <td>
                            <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'categorias:editar_producto' producto.pk %}')"><i class="far fa-edit"></i></button>
                            <a href="{% url 'categorias:inactivar_producto' producto.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
              </div>

{% endblock content %}

{% block js_page %}
 <script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock js_page %}

SistControl/catalogos/templates/catalogos/lista_subcategoria.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Subcategorías</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" href="{% url 'categorias:nueva_subcategoria' %}"><i class="far fa-calendar-plus"></i> Crear</a>
                      
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                {% if not subcategorias %}
                <div class="alert alert-info">No hay subcategorías para mostrar</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Categoría</th>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Estado</th>
                        <th>Creado</th>
                        <th>Modificado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for categ in subcategorias %}
                        <tr>
                            <td>{{categ.categoria}}</td>
                            <td>{{categ.id}}</td>
                            <td>{{categ.nombre}}</td>
                            <td>{{categ.estado|yesno:"Activo, Inactivo"}}</td>
                            <td>{{categ.created|date:"d/m/y H:i:s"}}</td>
                            <td>{{categ.updated|date:"d/m/y H:i:s"}}</td>
                            <td>
                            <a href="{% url 'categorias:editar_subcategoria' categ.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'categorias:borrar_subcategoria' categ.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                </div>
              </div>

{% endblock content %}

{% block js_page %}
 <script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
  </script>
{% endblock js_page %}